"""Playwright script generation and execution.

Test scripts are generated by the LLM as standard `@playwright/test` JavaScript and
executed by the real Playwright test runner in an **isolated subprocess** (see
`run_playwright_test`). This replaces the previous in-process `exec()`/`eval()` of
model output, which was both non-functional (JS compiled as Python) and a remote
code-execution sink. The generated code is still untrusted, so it runs out-of-process
with a hard timeout and is killed if it overruns.
"""

import asyncio
import os
import shutil
import subprocess
import time
import uuid
from pathlib import Path

from app.services.ai_service import call_ai

# backend/playwright_runner — a small Node workspace with @playwright/test installed.
RUNNER_DIR = Path(__file__).resolve().parents[2] / "playwright_runner"
TESTS_DIR = RUNNER_DIR / "tests"


def _trim_failure_logs(logs: list[str], max_chars: int = 3500) -> str:
    """Join runner log lines, keeping the tail where Playwright prints the error."""
    text = "\n".join(logs)
    if len(text) <= max_chars:
        return text
    return "...(earlier output trimmed)...\n" + text[-max_chars:]


async def generate_playwright_script(
    test_case: dict,
    target_files: list[dict],
    global_instruction: str | None,
    base_url: str,
    failure_context: dict | None = None,
    custom_prompt: str | None = None,
) -> str:
    """Generate a Playwright (@playwright/test) script for a test case using the LLM.

    `failure_context` ({"script": str, "logs": list[str]}) carries the most recent
    failing script for this test case and its runner output. When present, the model
    is asked to diagnose that failure and repair it rather than regenerate blind —
    without it, regeneration at temperature 0 tends to repeat the same mistake.

    `custom_prompt` carries free-text instructions scoped to this run (from the
    execution modal's "Custom Prompt" field or the agent's run_tests tool), as
    opposed to `global_instruction` which applies to every run for the repo.
    """
    prompt = f"""You are a Playwright automation expert. Write a complete Playwright script to test the following scenario.

Test Case:
- Title: {test_case['title']}
- Description: {test_case['description']}
- Type: {test_case['type']}
- Target Route: {test_case.get('targetRoute', 'N/A')}
- Expected Result: {test_case.get('expectedResult', 'N/A')}

Target Application URL: {base_url}

"""
    if target_files:
        prompt += "\nRelevant Source Files (use these to derive accurate text, roles and routes):\n"
        for tf in target_files:
            prompt += f"\n--- {tf['path']} ---\n{tf['content'][:4000]}\n"

    if global_instruction:
        prompt += f"\nGlobal Instructions: {global_instruction}\n"

    if custom_prompt:
        prompt += (
            "\nRun-specific instructions from the user (apply to THIS test run, "
            f"they take priority over the global instructions): {custom_prompt}\n"
        )

    if failure_context and failure_context.get("script"):
        prompt += f"""
A PREVIOUS SCRIPT FOR THIS EXACT TEST CASE FAILED against the live app. Diagnose the
failure from the runner output below and write a script that avoids it. Typical root
causes: a locator that matched nothing or several elements (strict mode), a route or
label that does not exist, a page guarded by state (auth/cart), or an assertion on
unstable copy.

--- Previous failing script ---
{failure_context["script"][:6000]}

--- Runner output from the failed run ---
{_trim_failure_logs(failure_context.get("logs") or [])}

Do NOT repeat the failing selectors, routes or assertions unless the output proves they
were not the problem. If the output shows an element or text does not exist, target
something the source above confirms instead.
"""

    prompt += """
Write a complete Playwright script using the @playwright/test runner. Structure:

```javascript
const { test, expect } = require('@playwright/test');

test('descriptive test name', async ({ page }) => {
    // 1. Navigate to the target page (baseURL is preconfigured, relative paths work)
    // 2. Perform actions based on the test type
    // 3. Wait for elements to be visible/interactive
    // 4. Assert expected results
});
```

Rules:
- Use Playwright's locator strategies (getByRole, getByLabel, getByTestId, etc.)
- Add appropriate waits (waitForLoadState, waitForSelector, waitForURL)
- Handle loading states and network idle
- Add meaningful comments
- If the test type is 'api', use page.request to test endpoints
- If 'auth', test login/logout flows
- If 'form', test form submission with valid and invalid data
- If 'edge-case', test error states and boundary conditions

Write SIMPLE, ROBUST tests that pass against the real running app. A small number of
high-signal assertions is better than many brittle ones. Follow these strictly:
- Prefer web-first assertions that auto-wait, e.g. `await expect(locator).toBeVisible()`. Never use fixed `waitForTimeout` sleeps.
- Do NOT assert exact counts of dynamic/repeated lists (avoid `toHaveCount`). Instead assert the FIRST expected item is visible using `.first()`.
- NEVER use `toHaveText` on headings or prose: it requires the WHOLE string to match exactly, including line breaks/whitespace from the JSX, so it is extremely brittle. Use `toContainText(/short distinctive substring/i)` instead (e.g. `await expect(heroTitle).toContainText(/perfected/i)`).
- Match text with case-insensitive substrings/regex (e.g. `getByText(/screen repair/i)`), not full-string equality. Do not include `\n` or trailing punctuation in matchers.
- Do NOT hard-code prices, phone numbers, counts, or marketing copy you are not certain about. Assert on stable, structural things: headings, roles, nav links, key labels.
- Only assert visibility for elements actually rendered at the default desktop viewport (~1280px). Elements behind a mobile/hamburger menu are hidden on desktop — open the menu first or skip them.
- STRICT-MODE SAFETY (most common failure): a locator that matches more than one element makes Playwright throw. These are simple smoke tests, so append `.first()` to EVERY locator you assert on or click — e.g. `await expect(page.getByRole('link', { name: /get a free quote/i }).first()).toBeVisible()`. For navigation, additionally scope to the region and pass `exact: true` (e.g. `page.locator('nav').getByRole('link', { name: 'Services', exact: true }).first()`).
- FORM FIELDS need the SAME strict-mode care, and `.fill()`/`.click()` do NOT accept `.first()` chaining cleanly on ambiguous matches — they throw first. `getByLabel` does a SUBSTRING match, so `getByLabel('Password')` also matches "Confirm Password". For inputs, prefer the most specific locator available in the source: `page.locator('#password')` / `page.getByLabel('Password', { exact: true })` over a bare label. Distinguish "Password" from "Confirm Password" explicitly.
- Do NOT assume the order, position, or count of list/grid items. Never assert that a specific card/item is the "first" or "last". Only reference an item by text you can SEE verbatim in the source above; if you cannot confirm the exact text, assert structurally instead (e.g. that at least one card/heading of that type is visible).
- HUMAN-READABLE MESSAGES are unstable copy — this applies to BOTH UI toasts AND API JSON `message`/`error` fields. Never assert their exact words unless the string appears VERBATIM in the source above ("Login successful" vs "Login successful!" vs "Logged in successfully!" all differ). For a toast, assert the element becomes visible (e.g. `await expect(page.locator('#toast, .toast').first()).toBeVisible()`). For an API call, assert `expect(resp.ok()).toBeTruthy()` / `expect(resp.status()).toBe(201)` and structural fields (e.g. `expect(json.user.email).toBe(...)`), NOT `json.message`.
- MULTI-STEP / STATEFUL FLOWS (auth, cart, checkout, logout): the app starts with NO session — you must establish prerequisites IN THE TEST. To test logout, log in first; to test checkout or the cart page, add an item to the cart first; do not assume a logged-in user or a populated cart exists. Pages often guard on state (an empty cart redirects /checkout.html -> /cart.html), so seed the state before asserting.
- SESSION COOKIES: to seed state you MUST use `page.request` (e.g. `await page.request.post('/api/cart', { data: { productId: 1 } })`), NOT the standalone `request` test fixture. `page.request` shares the browser context's cookie jar with `page`, so the session you create is the same one `page.goto(...)` then sees. The `request` fixture has a SEPARATE cookie jar — state seeded through it is invisible to the page and the guard will still fire. Only use credentials/payloads/ids that appear in the source above.
- Only assert that a button/link exists if its label or href appears in the source above. To verify navigation, click it and assert `await expect(page).toHaveURL(/\\/route/)` rather than re-checking exact button text.
- Keep it to one focused `test(...)` block. Do not invent routes or selectors not supported by the source above.
- Return ONLY the JavaScript code inside a code block. No extra text.
"""

    # Reasoning tokens + the full script must fit; 4k truncated mid-script.
    text = await call_ai(prompt, temperature=0.0, max_tokens=12288)

    # Extract JS from a code block when present.
    if "```javascript" in text:
        text = text.split("```javascript")[1].split("```")[0]
    elif "```js" in text:
        text = text.split("```js")[1].split("```")[0]
    elif "```" in text:
        text = text.split("```")[1].split("```")[0]

    return text.strip()


def _resolve_npx() -> str | None:
    return shutil.which("npx") or shutil.which("npx.cmd")


async def run_playwright_test(
    playwright_script: str,
    base_url: str,
    timeout: int = 60000,
) -> dict:
    """Execute a generated Playwright script via the Node test runner in a subprocess.

    Returns a dict with logs, duration_ms, screenshot path (if any) and a success flag
    derived from the runner's exit code.

    With TEST_RUNNER=github-actions the execution is delegated to a CI runner
    (same result contract) so this process never launches Chromium.
    """
    from app.core.config import get_settings

    if get_settings().TEST_RUNNER == "github-actions":
        from app.services.actions_runner import run_playwright_test_on_actions

        return await run_playwright_test_on_actions(playwright_script, base_url, timeout)

    logs: list[str] = []
    start_time = time.time()

    def log(msg: str):
        logs.append(msg)

    def result(success: bool, error: str | None = None, screenshot: str | None = None) -> dict:
        duration = (time.time() - start_time) * 1000
        log(f"[SYSTEM] Test completed in {duration:.0f}ms")
        return {
            "logs": logs,
            "duration_ms": duration,
            "screenshot": screenshot,
            "success": success,
            "error": error,
        }

    log(f"[SYSTEM] Starting Playwright test execution against {base_url}")
    log(f"[SYSTEM] Script length: {len(playwright_script)} characters")

    npx = _resolve_npx()
    if not npx:
        log("[SYSTEM ERROR] 'npx' was not found on PATH. Install Node.js and run "
            "'npm install' in backend/playwright_runner.")
        return result(False, error="npx not found")

    if not (RUNNER_DIR / "node_modules").exists():
        log("[SYSTEM ERROR] Playwright runner is not installed. Run 'npm install' in "
            "backend/playwright_runner (and 'npx playwright install chromium').")
        return result(False, error="playwright runner not installed")

    TESTS_DIR.mkdir(parents=True, exist_ok=True)
    spec_name = f"generated_{uuid.uuid4().hex}.spec.js"
    spec_path = TESTS_DIR / spec_name
    spec_path.write_text(playwright_script, encoding="utf-8")

    env = dict(os.environ)
    env["PW_BASE_URL"] = base_url
    browsers_path = get_browsers_path()
    if browsers_path:
        env["PLAYWRIGHT_BROWSERS_PATH"] = browsers_path

    log("[SYSTEM] Launching Playwright test runner (isolated subprocess)...")
    success = False
    error: str | None = None

    # Run the blocking subprocess in a worker thread rather than via
    # asyncio.create_subprocess_exec. On Windows, uvicorn selects the
    # SelectorEventLoop whenever it runs with a subprocess (e.g. `--reload`),
    # and that loop raises NotImplementedError on create_subprocess_exec.
    # subprocess.run in a thread works regardless of the active event loop.
    def _run_blocking() -> subprocess.CompletedProcess:
        return subprocess.run(
            [npx, "playwright", "test", f"tests/{spec_name}", "--reporter=line"],
            cwd=str(RUNNER_DIR),
            env=env,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=timeout / 1000,
        )

    try:
        completed = await asyncio.to_thread(_run_blocking)

        output = (completed.stdout or "") + (completed.stderr or "")
        for line in output.splitlines():
            if line.strip():
                log(f"[BROWSER] {line}")

        success = completed.returncode == 0
        if success:
            log("[SYSTEM] Test passed")
        else:
            log(f"[SYSTEM ERROR] Test failed (exit code {completed.returncode})")
            error = "Test assertions failed or the script errored"
    except subprocess.TimeoutExpired:
        log(f"[SYSTEM ERROR] Test execution timed out after {timeout}ms")
        return result(False, error="timeout")
    except Exception as e:  # noqa: BLE001
        log(f"[SYSTEM ERROR] Failed to run test: {e}")
        error = str(e)
    finally:
        try:
            spec_path.unlink(missing_ok=True)
        except OSError:
            pass

    return result(success, error=error)


def get_browsers_path() -> str:
    from app.core.config import get_settings
    return get_settings().PLAYWRIGHT_BROWSERS_PATH
