"""Playwright script generation and execution.

Test scripts are generated by the LLM as standard `@playwright/test` JavaScript and
executed by the real Playwright test runner in an **isolated subprocess** (see
`run_playwright_test`). This replaces the previous in-process `exec()`/`eval()` of
model output, which was both non-functional (JS compiled as Python) and a remote
code-execution sink. The generated code is still untrusted, so it runs out-of-process
with a hard timeout and is killed if it overruns.
"""

import asyncio
import os
import shutil
import time
import uuid
from pathlib import Path

from app.services.ai_service import call_ai

# backend/playwright_runner — a small Node workspace with @playwright/test installed.
RUNNER_DIR = Path(__file__).resolve().parents[2] / "playwright_runner"
TESTS_DIR = RUNNER_DIR / "tests"


async def generate_playwright_script(
    test_case: dict,
    target_files: list[dict],
    global_instruction: str | None,
    base_url: str,
) -> str:
    """Generate a Playwright (@playwright/test) script for a test case using the LLM."""
    prompt = f"""You are a Playwright automation expert. Write a complete Playwright script to test the following scenario.

Test Case:
- Title: {test_case['title']}
- Description: {test_case['description']}
- Type: {test_case['type']}
- Target Route: {test_case.get('targetRoute', 'N/A')}
- Expected Result: {test_case.get('expectedResult', 'N/A')}

Target Application URL: {base_url}

"""
    if target_files:
        prompt += "\nRelevant Source Files:\n"
        for tf in target_files:
            prompt += f"\n--- {tf['path']} ---\n{tf['content'][:1500]}\n"

    if global_instruction:
        prompt += f"\nGlobal Instructions: {global_instruction}\n"

    prompt += """
Write a complete Playwright script using the @playwright/test runner. Structure:

```javascript
const { test, expect } = require('@playwright/test');

test('descriptive test name', async ({ page }) => {
    // 1. Navigate to the target page (baseURL is preconfigured, relative paths work)
    // 2. Perform actions based on the test type
    // 3. Wait for elements to be visible/interactive
    // 4. Assert expected results
});
```

Rules:
- Use Playwright's locator strategies (getByRole, getByLabel, getByTestId, etc.)
- Add appropriate waits (waitForLoadState, waitForSelector, waitForURL)
- Handle loading states and network idle
- Add meaningful comments
- Make assertions specific and testable
- If the test type is 'api', use page.request to test endpoints
- If 'auth', test login/logout flows
- If 'form', test form submission with valid and invalid data
- If 'edge-case', test error states and boundary conditions
- Return ONLY the JavaScript code inside a code block. No extra text.
"""

    text = await call_ai(prompt, temperature=0.2)

    # Extract JS from a code block when present.
    if "```javascript" in text:
        text = text.split("```javascript")[1].split("```")[0]
    elif "```js" in text:
        text = text.split("```js")[1].split("```")[0]
    elif "```" in text:
        text = text.split("```")[1].split("```")[0]

    return text.strip()


def _resolve_npx() -> str | None:
    return shutil.which("npx") or shutil.which("npx.cmd")


async def run_playwright_test(
    playwright_script: str,
    base_url: str,
    timeout: int = 60000,
) -> dict:
    """Execute a generated Playwright script via the Node test runner in a subprocess.

    Returns a dict with logs, duration_ms, screenshot path (if any) and a success flag
    derived from the runner's exit code.
    """
    logs: list[str] = []
    start_time = time.time()

    def log(msg: str):
        logs.append(msg)

    def result(success: bool, error: str | None = None, screenshot: str | None = None) -> dict:
        duration = (time.time() - start_time) * 1000
        log(f"[SYSTEM] Test completed in {duration:.0f}ms")
        return {
            "logs": logs,
            "duration_ms": duration,
            "screenshot": screenshot,
            "success": success,
            "error": error,
        }

    log(f"[SYSTEM] Starting Playwright test execution against {base_url}")
    log(f"[SYSTEM] Script length: {len(playwright_script)} characters")

    npx = _resolve_npx()
    if not npx:
        log("[SYSTEM ERROR] 'npx' was not found on PATH. Install Node.js and run "
            "'npm install' in backend/playwright_runner.")
        return result(False, error="npx not found")

    if not (RUNNER_DIR / "node_modules").exists():
        log("[SYSTEM ERROR] Playwright runner is not installed. Run 'npm install' in "
            "backend/playwright_runner (and 'npx playwright install chromium').")
        return result(False, error="playwright runner not installed")

    TESTS_DIR.mkdir(parents=True, exist_ok=True)
    spec_name = f"generated_{uuid.uuid4().hex}.spec.js"
    spec_path = TESTS_DIR / spec_name
    spec_path.write_text(playwright_script, encoding="utf-8")

    env = dict(os.environ)
    env["PW_BASE_URL"] = base_url
    browsers_path = get_browsers_path()
    if browsers_path:
        env["PLAYWRIGHT_BROWSERS_PATH"] = browsers_path

    log("[SYSTEM] Launching Playwright test runner (isolated subprocess)...")
    success = False
    error: str | None = None
    try:
        proc = await asyncio.create_subprocess_exec(
            npx, "playwright", "test", f"tests/{spec_name}", "--reporter=line",
            cwd=str(RUNNER_DIR),
            env=env,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
        )
        try:
            stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=timeout / 1000)
        except asyncio.TimeoutError:
            proc.kill()
            await proc.wait()
            log(f"[SYSTEM ERROR] Test execution timed out after {timeout}ms")
            return result(False, error="timeout")

        output = stdout.decode("utf-8", errors="replace") if stdout else ""
        for line in output.splitlines():
            if line.strip():
                log(f"[BROWSER] {line}")

        success = proc.returncode == 0
        if success:
            log("[SYSTEM] Test passed")
        else:
            log(f"[SYSTEM ERROR] Test failed (exit code {proc.returncode})")
            error = "Test assertions failed or the script errored"
    except Exception as e:  # noqa: BLE001
        log(f"[SYSTEM ERROR] Failed to run test: {e}")
        error = str(e)
    finally:
        try:
            spec_path.unlink(missing_ok=True)
        except OSError:
            pass

    return result(success, error=error)


def get_browsers_path() -> str:
    from app.core.config import get_settings
    return get_settings().PLAYWRIGHT_BROWSERS_PATH
