from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.schemas.schemas import TestRunOut, TestRunRequest
from app.models.models import TestCase, TestRun, User, Repository
from app.core.database import get_db
from app.core.security import get_current_user
from app.services.playwright_service import generate_playwright_script, run_playwright_test
from app.services.github_service import get_github_file

router = APIRouter(prefix="/api/test-cases/run", tags=["test-execution"])


@router.post("")
@router.post("/")
async def run_test_cases(
    body: TestRunRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Generate Playwright scripts and execute tests in a real browser."""
    results = []
    access_token = current_user.github_access_token

    for tc_id in body.test_case_ids:
        result = await db.execute(
            select(TestCase).where(TestCase.id == tc_id, TestCase.user_id == current_user.id)
        )
        tc = result.scalar_one_or_none()
        if not tc:
            continue

        # Fetch repo for global instruction (only when the test case is linked to one).
        global_instruction = None
        if tc.repo_id:
            repo_result = await db.execute(
                select(Repository).where(
                    Repository.id == tc.repo_id, Repository.user_id == current_user.id
                )
            )
            repo = repo_result.scalar_one_or_none()
            global_instruction = repo.global_instruction if repo else None

        # Get target file contents for additional context.
        target_files = []
        if access_token and tc.target_files:
            for path in tc.target_files:
                content = await get_github_file(
                    access_token, tc.repo_owner, tc.repo_name, path, tc.branch
                )
                if content:
                    target_files.append(content)

        # Generate or reuse the cached script.
        script = tc.playwright_script
        if body.mode == "generate" or not script:
            try:
                script = await generate_playwright_script(
                    test_case={
                        "title": tc.title,
                        "description": tc.description,
                        "type": tc.test_type,
                        "targetRoute": tc.target_route,
                        "expectedResult": tc.expected_result,
                    },
                    target_files=target_files,
                    global_instruction=global_instruction,
                    base_url=body.base_url,
                )
            except RuntimeError as e:
                results.append({
                    "test_case_id": tc_id,
                    "status": "failed",
                    "logs": [f"[SYSTEM ERROR] {e}"],
                    "error": str(e),
                })
                continue
            if not script:
                results.append({
                    "test_case_id": tc_id,
                    "status": "failed",
                    "logs": ["[SYSTEM ERROR] Failed to generate Playwright script"],
                    "error": "No script generated by AI",
                })
                continue
            tc.playwright_script = script
            await db.commit()

        # Execute in a real browser (isolated subprocess).
        exec_result = await run_playwright_test(script, body.base_url)

        status = "passed" if exec_result["success"] else "failed"
        logs = exec_result["logs"]

        test_run = TestRun(
            test_case_id=tc.id,
            user_id=current_user.id,
            status=status,
            logs=logs,
            error_message=exec_result.get("error") if not exec_result["success"] else None,
            duration_ms=exec_result["duration_ms"],
            playwright_script_used=script,
        )
        db.add(test_run)

        tc.status = status
        tc.logs = logs
        tc.duration_ms = exec_result["duration_ms"]
        await db.commit()

        results.append({
            "test_case_id": tc_id,
            "status": status,
            "logs": logs,
            "error": exec_result.get("error") if not exec_result["success"] else None,
            "playwright_script": script,
            "duration_ms": exec_result["duration_ms"],
        })

    return {"results": results}


@router.get("/runs/{test_case_id}", response_model=list[TestRunOut])
async def get_test_runs(
    test_case_id: int,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    # Ensure the test case belongs to the caller before exposing its run history.
    owner = await db.execute(
        select(TestCase).where(TestCase.id == test_case_id, TestCase.user_id == current_user.id)
    )
    if owner.scalar_one_or_none() is None:
        raise HTTPException(status_code=404, detail="Test case not found")

    result = await db.execute(
        select(TestRun)
        .where(TestRun.test_case_id == test_case_id, TestRun.user_id == current_user.id)
        .order_by(TestRun.created_at.desc())
    )
    return result.scalars().all()
